name: bloc_weather
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  hydrated_bloc: ^9.1.0
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  path_provider: ^2.0.13
  google_fonts: ^4.0.3
  weather_repository:
    path: packages/weather_repository


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  mocktail: ^0.3.0
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1


flutter:
  uses-material-design: true
  assets:
    - assets/

